%% EventCatalog Mermaid Diagram
%% Resource: commands/RegistreerAanvraagKotlabelApiRequest (v1.0.0)
%% Generated: 2026-03-21T20:37:19.240Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    RegistreerAanvraagKotlabelApiRequest_1_0_0>"Registreer Aanvraag Kotlabel (1.0.0)"]:::commands
    IntegrationProcessFormulierenLoket_1_0_0[["IntegrationProcess FormulierenLoket (1.0.0)"]]:::services
    AanvragenService_1_0_0[["AanvragenService (1.0.0)"]]:::services

    %% Edges
    IntegrationProcessFormulierenLoket_1_0_0 -->|"invokes"| RegistreerAanvraagKotlabelApiRequest_1_0_0
    RegistreerAanvraagKotlabelApiRequest_1_0_0 -->|"accepts"| AanvragenService_1_0_0