
export default new Map([
["../domains/Aanvragen/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Core/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FCore%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/IntegrationProcessStatus/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FIntegrationProcessStatus%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/IntegrationProcessFormulierenLoket/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FIntegrationProcessFormulierenLoket%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Core/services/DocumentenModuleService/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FCore%2Fservices%2FDocumentenModuleService%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Core/services/RestApiService/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FCore%2Fservices%2FRestApiService%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/LoketWebhookEndpoint/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FLoketWebhookEndpoint%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/events/BestemmingVoorAanvraagGeregistreerdEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Fevents%2FBestemmingVoorAanvraagGeregistreerdEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/events/NieuweAanvraagGeregistreerdEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Fevents%2FNieuweAanvraagGeregistreerdEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/LoketWebhookEndpoint/events/FormulierAanvraagKotlabelSubmittedEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FLoketWebhookEndpoint%2Fevents%2FFormulierAanvraagKotlabelSubmittedEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/IntegrationProcessStatus/events/NieuweAanvraagDosisInfoMessageEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FIntegrationProcessStatus%2Fevents%2FNieuweAanvraagDosisInfoMessageEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/IntegrationProcessStatus/events/NieuweAanvraagDosisDossierMessageEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FIntegrationProcessStatus%2Fevents%2FNieuweAanvraagDosisDossierMessageEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/IntegrationProcessStatus/events/NieuweAanvraagNotificatieMessageEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FIntegrationProcessStatus%2Fevents%2FNieuweAanvraagNotificatieMessageEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/commands/RegistreerAanvraagKotlabelApiRequest/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Fcommands%2FRegistreerAanvraagKotlabelApiRequest%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Core/services/RestApiService/commands/UploadDocumentRequest/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FCore%2Fservices%2FRestApiService%2Fcommands%2FUploadDocumentRequest%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/flows/BestemmingVoorAanvraagGeregistreerdSagaFlow/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fflows%2FBestemmingVoorAanvraagGeregistreerdSagaFlow%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/flows/FormulierAanvraagKotlabelSubmittedFlow/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fflows%2FFormulierAanvraagKotlabelSubmittedFlow%2Findex.mdx&astroContentModuleFlag=true")],
["../pages/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fpages%2Findex.mdx&astroContentModuleFlag=true")]]);
		