
export default new Map([
["../domains/Aanvragen/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/IntegrationProcessesFormulierenLoket/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FIntegrationProcessesFormulierenLoket%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/LoketWebhookService/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FLoketWebhookService%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/events/NieuweAanvraagGeregistreerdEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Fevents%2FNieuweAanvraagGeregistreerdEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/events/BestemmingVoorAanvraagGeregistreerdEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Fevents%2FBestemmingVoorAanvraagGeregistreerdEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/AanvragenService/commands/RegistreerAanvraagKotlabelApiRequest/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FAanvragenService%2Fcommands%2FRegistreerAanvraagKotlabelApiRequest%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/services/LoketWebhookService/events/FormulierAanvraagKotlabelSubmittedEvent/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fservices%2FLoketWebhookService%2Fevents%2FFormulierAanvraagKotlabelSubmittedEvent%2Findex.mdx&astroContentModuleFlag=true")],
["../channels/payment.{env}.events/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fchannels%2Fpayment.%7Benv%7D.events%2Findex.mdx&astroContentModuleFlag=true")],
["../channels/inventory.{env}.events/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fchannels%2Finventory.%7Benv%7D.events%2Findex.mdx&astroContentModuleFlag=true")],
["../channels/orders.{env}.events/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fchannels%2Forders.%7Benv%7D.events%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/flows/BestemmingVoorAanvraagGeregistreerdSaga/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fflows%2FBestemmingVoorAanvraagGeregistreerdSaga%2Findex.mdx&astroContentModuleFlag=true")],
["../pages/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fpages%2Findex.mdx&astroContentModuleFlag=true")],
["../domains/Aanvragen/flows/FormulierAanvraagKotlabelSubmittedFlow/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=..%2Fdomains%2FAanvragen%2Fflows%2FFormulierAanvraagKotlabelSubmittedFlow%2Findex.mdx&astroContentModuleFlag=true")]]);
		