%% EventCatalog Mermaid Diagram
%% Resource: services/DocumentenModuleService (v1.0.0)
%% Generated: 2026-03-21T20:37:19.275Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    DocumentenModuleService_1_0_0[["VLOK Documenten Module (1.0.0)"]]:::services

    %% Edges