%% EventCatalog Mermaid Diagram
%% Resource: services/LoketWebhookEndpoint (v1.0.0)
%% Generated: 2026-03-21T20:37:19.274Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff

    %% Nodes
    LoketWebhookEndpoint_1_0_0[["Loket Webhook Endpoint (1.0.0)"]]:::services
    FormulierAanvraagKotlabelSubmittedEvent_1_0_0>"Formulier Aanvraag Kotlabel Submitted (1.0.0)"]:::events
    IntegrationProcessFormulierenLoket_1_0_0[["IntegrationProcess FormulierenLoket (1.0.0)"]]:::services

    %% Edges
    LoketWebhookEndpoint_1_0_0 -->|"publishes  event"| FormulierAanvraagKotlabelSubmittedEvent_1_0_0
    FormulierAanvraagKotlabelSubmittedEvent_1_0_0 -->|"subscribed by"| IntegrationProcessFormulierenLoket_1_0_0